name: Avi Aryan
markdown: redcarpet
fullpath: http://aviaryan.in
description: Personal Website
baseurl: 
permalink: /blog/:categories/:title.html
title: Avi Aryan
paginate: 10
highlighter: pygments

# More
author:
    fullname: Avi Aryan
    twitter: aviaryan123
    github: aviaryan
    facebook: avi.aryan.ap
    google: AviAryan
    gplusid: 110328513842183229282

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
disqusid: avi-aryan-github
disqusurl: http://aviaryan.github.io
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']